spring:
  application:
    name: algorithm
server:
  port: 8443
  ssl:
    key-store: classpath:lucifer.keystore
    key-password: lucifer
    key-store-type: JKS
    key-alias: tomcat

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      register-with-eureka: true
      fetch-registry: true